config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {registrations: "users_devise/registrations", omniauth_callbacks: :callbacks}
  #devise_for :users, controllers: {omniauth_callbacks: :callbacks}
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show
  resources :notifications, only: [:index, :show]

  get "tags/:tag", to: "posts#index", as: :tag
  get "/chatwork", to: "chatwork#index"
  post "/chatwork", to: "chatwork#send_message"

end

app/controllers/chatwork_controller.rb
class ChatworkController < ApplicationController
  def index
  end

  def send_message
    ChatWork.api_key = "efeb7b956422c8a4d2bdc97d29fc9b0c"
    name = params["/chatwork"][:name]
    account_id = params["/chatwork"][:user_id]
    room_id = params["/chatwork"][:room_id]
    message_body = "[To:#{account_id}] #{name}\n #{params["/chatwork"][:content]}"
    ChatWork::Message.create room_id: room_id, body: message_body
    redirect_to root_path
  end
end

app/views/chatwork/index.html.erb
<%= form_for chatwork_path, method: :post do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="form-group">
    <%= f.label :room_id %>
    <%= f.text_field :room_id %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div><%= submit_tag t "sent_message" %></div>
<% end %>