config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {registrations: "users_devise/registrations", omniauth_callbacks: :callbacks}
  #devise_for :users, controllers: {omniauth_callbacks: :callbacks}
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show
  resources :notifications, only: [:index, :show]

  get "tags/:tag", to: "posts#index", as: :tag
  get "/chatwork", to: "chatwork#index"
  post "/chatwork", to: "chatwork#send_message"

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user, presence: true
  validates :content, presence: true

  acts_as_tree order: "created_at ASC"

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]

  def create
    if params[:comment][:parent_id].to_i > 0
      parent = Comment.find_by id: params[:comment].delete(:parent_id)
      @comment = parent.children.build comment_params
    else
      @comment = Comment.new comment_params
    end

    if @comment.save
      NotificationServices::CreateNotification.new(comment: @comment,
        current_user_id: current_user.id).create_notification
      respond_to do |format|
        format.html{redirect_to :back}
        format.js
      end
    end
  end

  def destroy
    @comment.descendants.each do |comment_des|
      comment_des.destroy
    end
    @comment.destroy
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit :post_id, :user_id, :content
  end

  def set_comment
    @comment = Comment.find_by id: params[:id]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for comments, post, comment_new
    safe_join(comments.map do |comment, nested_comments|
      render(comment, post: post,
        comment_new: comment_new) + tree(nested_comments, post)
    end)
  end

  def tree nested_comments, post
    unless nested_comments.empty?
      content_tag :div,
        comments_tree_for(nested_comments, post, Comment.new), class: "replies"
    end
  end
end

app/views/comments/_comment.html.erb
<div id="form-comment<%= post.id %>">
  <div class="row">
    <div class="one columns">
      <%= image_tag "avatar.jpg", class: "image-user" %>
    </div>
    <div class="eleven columns">
      <%= link_to (comment.user.profile&.name || comment.user.name), user_path(comment.user_id) %>:
      <span class="timestamp">
        <%= comment.created_at %>
      </span><br/>
      <p><%= comment.content %><p>
        <%= link_to t("posts.show.delete"), post_comment_path(post, comment),
          method: :delete,
          data: {confirm: t("posts.show.sure")} %>
    </div>
  </div>
</div>
<div class="row">
  <div class="one columns"></div>
  <div class="eleven columns">
    <%= render "comments/comment_form", post: post, parent_id: comment.id,
      comment_new: comment_new %>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<% if user_signed_in? %>
    <%= form_for [post, comment_new], html: {id: "form-comment"} do |f| %>
      <%= f.hidden_field :parent_id, value: parent_id %>
      <%= f.hidden_field :post_id, value: post.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.text_area :content, placeholder: "Comment",
        required: true, class: "u-full-width add-comment" %>
    <% end %>
<% end %>
<br />

app/views/comments/create.js.erb
$('#form-comment<%= @comment.post_id %>').append("<%= j render(@comment) %>");
$('#form-comment form textarea').val('');