config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users, controllers: {registrations: "users_devise/registrations", omniauth_callbacks: :callbacks}
  #devise_for :users, controllers: {omniauth_callbacks: :callbacks}
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :users, only: :show
  resources :notifications, only: [:index, :show]

  get "tags/:tag", to: "posts#index", as: :tag
  get "/chatwork", to: "chatwork#index"
  post "/chatwork", to: "chatwork#send_message"

end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  acts_as_taggable
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :notifications, as: :notificationable

  validates :content, presence: true
  validates :title, presence: true
end

app/models/supports/post.rb
class Supports::Post
  attr_reader :post, :posts

  def initialize post
    @post = post
  end

  def posts
    @posts ||= Post.all
  end

  def comment
    @comment = Comment.new
  end

  def comments_tree
    @comments = @post.comments
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts =
      if params[:tag]
        Post.tagged_with(params[:tag])
      else
        Post.all
      end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @supports = Supports::Post.new @post
    @comment = Comment.new
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build post_params

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :tag_list)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(post, html: {style: "width: 60%; margin-left: 20%;"}) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :tag_list, "Tags" %>
    <%= f.text_field :tag_list %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_vote_form.html.erb
<div id="vote_form">
  <% if user_signed_in? %>
    <% if (current_user.voted_down_on? post) || (!ActsAsVotable::Vote.where(voter_id: current_user,votable_id: post.id).present?) %>
      <%= link_to post_votes_path(post), method: :post, remote: true do %>
        <%= image_tag "unlike.png" %>
      <% end %>
    <% else %>
      <%= link_to post_vote_path(post,0), method: :delete, remote: true do %>
        <%= image_tag "like.png" %>
      <% end %>
    <% end %>
  <% end %>
  <%= post.get_upvotes.size %> <%= t "posts.show.like" %>
  <%= raw post.votes_for.up.by_type(User).voters.map { |voter| link_to voter.profile&.name || voter&.name, "#" }.join(', ') %>
</div>

app/views/posts/edit.html.erb
<h1 style="width: 60%; margin-left: 20%; text-align: center;">Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div style="width: 80%; margin-left: 10%;">
  <% if user_signed_in? %>
    <div style="float: right;">
      Hi <%= current_user.profile&.name %>
      <%= link_to notifications_path, class: "dropdown-toggle", id: "noti-count",
        data: {toggle: "dropdown"}, aria: {haspopup: "true", expanded: "false"},
        remote: true do %>
        <%= image_tag "bell.png" %>
        <span class="notification-number"><%= number %></span>
        <span class="caret"></span>
      <% end %>
      <p>
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      <% end %>
      </p>
    </div>
  <% end %>
</div>
<div style="clear: both;"></div>
<h1 style="text-align: center;">Blogs of Tien</h1>
<%= link_to 'New Post', new_post_path, {style: "margin-left: 10%;", class: "button"} %>

<div class="index align-left" style="margin-left: 10%; width: 80%;">
  <!-- Definition List -->

  <section>
   <!--  <header>
      <h3>Follow me <code style="color: red;">ptnk1995</code></h3><br/>
      <%= image_tag "tien.jpg", style: "" %>
      <ul class="icons">
        <li><a href="#" class="icon style1 fa-twitter"><span class="label">Twitter</span></a></li>
        <li><a href="#" class="icon style1 fa-facebook"><span class="label">Facebook</span></a></li>
        <li><a href="#" class="icon style1 fa-instagram"><span class="label">Instagram</span></a></li>
        <li><a href="#" class="icon style1 fa-github"><span class="label">Github</span></a></li>
        <li><a href="#" class="icon style1 fa-dribbble"><span class="label">Dribbble</span></a></li>
      </ul>

    </header> -->
    <div class="content">
      <% @posts.each do |post| %>
        <div >
        <h2><%= post.title %></h2>
        <%= raw post.tag_list.map { |t| link_to t, tag_path(t), class: "button small" }.join(' ') %>
        <p><%= post.content %></p>
        <%= link_to 'Show', post %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
        <hr />
      <% end %>
    </div>
  </section>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div style="width: 80%; margin-left: 10%;">
  <p>
    <strong><h3 style="text-align: center;"><%= @post.title %></h3></strong>
  </p>

  <p>
    <%= @post.content %>
  </p>
  <p>
    <strong>Tags:</strong>
    <%= raw @post.tag_list.map { |t| link_to t, tag_path(t), class: "btn-sm btn-default" }.join(' ') %>
  </p>

  <%= render "vote_form", post: @post %>

  <%= link_to 'Edit', edit_post_path(@post) %> |
  <%= link_to 'Back', posts_path %>
    <%= render "comments/comment_form", post: @post, parent_id: nil, comment_new: @comment %>
    <%= comments_tree_for @supports.comments_tree.hash_tree(limit_depth: 5),
        @post, @supports.comment %>
</div>